version: "3"

services:

  #######################################
  # Nginx: gateway
  #######################################
  nginx-gateway:
    image: nginx:1.17.8-alpine
    container_name: nginx-gateway
    volumes:
     - ./nginx-gateway/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
      - web
      - mariadb
      - phpmyadmin
    ports:
      - 80:80

  #######################################
  # MariaDB: MariaDB database
  #######################################
  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=1234 --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 15s
      retries: 20

  #######################################
  # phpMyadmin
  #######################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOSTS: mariadb
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 8080:80

  #######################################
  # api
  #######################################
  api:
    build: ./api/
    container_name: api
    restart: always
    # ports:
    #   - 9000:9000

  #######################################
  # web
  #######################################
  web:
    build: ./web/
    container_name: web
    restart: always
    # ports:
    #   - 3000:3000
