version: "3"

services:

  #######################################
  # Nginx: gateway
  #######################################
  nginx-gateway:
    image: nginx:1.17.8-alpine
    container_name: nginx-gateway
    volumes:
     - ./nginx-gateway/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
      - web
    ports:
      - 80:80

  #######################################
  # api
  #######################################
  api:
    build: ./api/
    container_name: api
    restart: always
    # ports:
    #   - 9000:9000

  #######################################
  # web
  #######################################
  web:
    build: ./web/
    container_name: web
    restart: always
    # ports:
    #   - 3000:3000
