version: "3"

services:

  #######################################
  # MariaDB: MariaDB database
  #######################################
  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=1234 --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 15s
      retries: 20

  #######################################
  # phpMyadmin
  #######################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOSTS: mariadb
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 8080:80
